config/routes.rb
Rails.application.routes.draw do
  # List all Invoices
  resources :invoices

  # Specific Batches Scope
  resources :batches do
    resources :invoices
    get 'process' => 'batches#process_nfe', as: :process
  end

  # RootRoute to batch upload
  root to: 'batches#index'
end

app/models/additional_info.rb
class AdditionalInfo < ActiveRecord::Base
  # Associations
  belongs_to :invoice
  belongs_to :parent, class_name: 'AdditionalInfo', foreign_key: 'parent_additional_info_id'
  has_many :child_additional_info, class_name: 'AdditionalInfo', foreign_key: 'parent_additional_info_id'

  # Rails Validation
  validates :key, presence: true

  # ========================    STATIC METHODS  ===================================
  def self.factory(hash, ref)
    hash.keys.each do |key|

    end


    ref.is_a?(AdditionalInfo) ? ref.child_additional_info << additional : ref.additional_infos << additional
  end
end

app/models/batch.rb
class Batch < ActiveRecord::Base
  # Concerns Dependencies
  include ProcessBatch
  include ProcessBatchDir
  include ProcessBatchCommands

  # Associations
  has_many :invoices

  # Upload GEM setting
  mount_uploader :attached, AttachmentUploader

  # Rails Validations
  validates :attached_file_name, length: { minimum: 4, maximum: 255 }, presence: true

  # Custom Validations
  validate :attached_type, on: :create

  # Readable file name
  def attached_file_name
    self.attached.filename
  end

  # Process the Batch
  def process_it
    # Prevent bugs
    return true if self.processed?

    # Setup Resp
    process_resp = {}
    process_resp[:unzipped] = unzip
    process_resp[:invoices] = setup_invoices
    process_resp[:tmp_removed] = remove_tmp

    # Update state
    self.processed = true
    self.save

    process_resp
  end

  private
    # Validate attached type
    def attached_type
      if self.attached.filename.downcase.index('.zip').nil?
        self.errors.add(:attached, 'A extensão deve ser .zip')
        raise ActiveRecord::Rollback
      end
    end
end

app/models/concerns/attachment.rb
module Attachment
  extend ActiveSupport::Concern

  # Upload validations for which include it
  included do
    has_attached_file :attached,
                      path: "#{self.to_s.downcase.pluralize}/:attachment/:id/:style/#{self.to_s.downcase}_work_flow",
                      styles: { original: '300x300>', thumb: '75x75>' },
                      default_url: 'defaults/how_works_flow.png', if: :attached?

    validates_attachment :attached, presence: true,
                         content_type: { content_type: 'application/zip' }, if: :attached?
  end

  def attached?
    self.attached_file_name
  end
end

app/models/concerns/process_batch.rb
module ProcessBatch
  extend ActiveSupport::Concern

  # Persist & Process it invoices
  def setup_invoices
    # Get the unzipped files on the folder
    files = Dir.glob("#{unzipped_target_folder}/*")

    # Setup it Invoices
    files.each do |file|
      next if file.index('.xml').nil?
      nfe_xml = File.open(file, 'rb').read
      hash_invoice = Hash.from_xml(nfe_xml).deep_symbolize_keys!

      invoice_params = {nfe_code: hash_invoice[:NFe][:infNFe][:Id], body: nfe_xml}
      current_invoice = Invoice.new(invoice_params)
      self.invoices << current_invoice
    end
  end
end

app/models/concerns/process_batch_commands.rb
module ProcessBatchCommands
  extend ActiveSupport::Concern

  # Command: to unzip it ZIP batch file
  def unzip
    cmd = "unzip #{zip_folder} -d #{unzipped_target_folder}"
    system cmd
  end

  # Remove the unzipped files
  def remove_tmp
    cmd = "rm -rf #{unzipped_target_folder}"
    system cmd
  end
end

app/models/concerns/process_batch_dir.rb
module ProcessBatchDir
  extend ActiveSupport::Concern

  # Retrieve it project upload zipped files
  def zip_folder
    self.attached.path
  end

  # The unzip destination folder
  def unzipped_target_folder
    "#{Rails.root.join('public')}/unzipped/tmp"
  end
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  # Associations
  belongs_to :batch
  has_many :additional_infos

  # Rails Validations
  validates :nfe_code, length: { minimum: 5, maximum: 75}, presence: true
  validates :body, length: { minimum: 10 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :set_batch, only: [:show, :edit, :process_nfe, :destroy]

  # GET /batches
  # GET /batches.json
  def index
    @batches = Batch.all
  end

  # # GET /batches/1
  # # GET /batches/1.json
  # def show
  # end

  # GET /batches/new
  def new
    @batch = Batch.new
  end

  # # GET /batches/1/edit
  # def edit
  # end
  #
  # POST /batches
  # POST /batches.json
  def create
    @batch = Batch.new(batch_params)

    respond_to do |format|
      if @batch.save
        format.html { redirect_to @batch, notice: 'Batch was successfully created.' }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render :new }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1
  # DELETE /batches/1.json
  def destroy
    @batch.destroy
    respond_to do |format|
      format.html { redirect_to batches_url, notice: 'Batch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /batches/1/process
  def process_nfe
    @batch.process_it
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_batch
      params[:id].nil? ? batch_id = params[:batch_id] : batch_id = params[:id]
      @batch = Batch.find(batch_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def batch_params
      params.require(:batch).permit(:attached)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  # GET /invoices
  # GET /invoices.json
  def index
  end

  # GET /show/1
  # GET /show/1.json
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def aside_grouped_actions
    [
      {
          label: 'Listagem de Registros',
          actions: [
            {name: 'Lotes de NF-e', icon: 'large-icon ion-ios-box-outline', link: batches_path},
            {name: 'NF-e avulsas', icon: 'large-icon ion-ios-paper-outline', link: invoices_path}
          ]
      }
    ]
  end
end

app/helpers/batche_zips_helper.rb
module BatcheZipsHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/views/batches/_form.html.slim
= form_for @batch do |f|
  - current_obj = @batch
  - if current_obj.errors.any?
    .alert.alert-border-left
      strong = "Atenção. #{pluralize(current_obj.errors.count, "erro")} impediu o Projeto de ser registrada:"
      ul.style_warning_list
        - current_obj.errors.full_messages.each do |message|
          li = message

  .spacing_rows
    .row
      .col.l8.offset-l2
        .upload-avatar.file-field.input-field
          input class="file-path validate" type="text"
          .btn
            span File
            = f.file_field :attached, onchange: 'show_brand(this, "#work_flow")'

    .row
      .col.l6.offset-l4
        =f.submit 'Submeter Lote para Processamento', class: 'btn'


javascript:
  // show the Ad dynamic after it "upload_intent"
  function show_brand(input, img_ref) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        $('.file-path').val(input.files[0].name);
        $(img_ref).attr('src', e.target.result);
      };
      reader.readAsDataURL(input.files[0]);
    }
  }

app/views/batches/edit.html.slim
h1 Editing batch

== render 'form'

= link_to 'Show', @batch
'|
= link_to 'Back', batches_path

app/views/batches/index.html.slim
h1.center
  i.ion-filing
  = ' Lista de Lotes Enviados'

= link_to new_batch_path, class: 'right btn-floating btn-large white-text' do
  i.ion-plus-round

.divider

table.table-striped
  thead
    tr
      th Data
      th Horário
      th.center Processar
      th.center Visualizar
      th.center Deletar

  tbody
    - @batches.each do |batch|
      tr
        td = batch.created_at.strftime('%d/%m/%Y')
        td = batch.created_at.strftime('%H:%M:%S')
        td.center
          -if batch.processed?
            =link_to root_path do
              i.large-icon.ion-flash-off
          -else
            =link_to batch_process_path(batch) do
              i.large-icon.ion-flash
        td.center
          = link_to batch do
            i.large-icon.ion-ios-eye
        td.center
          = link_to batch, method: :delete, data: {confirm: 'Certeza de que quer Deletar?'} do
            i.large-icon.ion-trash-b.red-text

app/views/batches/new.html.slim
h1.center
  i.ion-upload
  = ' Upload de Novo Lote de Notas'

= render 'form'

.row
  = link_to batches_path, class: 'btn-floating btn-large waves-effect waves-light blue-grey' do
    i.ion-android-arrow-back

app/views/batches/show.html.slim
h1.center
  i.ion-filing
  = ' Notas Fiscais Processadas'
h3.center
  =" Lote: #{@batch.created_at.strftime('%d/%m/%Y')} - #{@batch.created_at.strftime('%H:%M:%S')}"

  = link_to new_batch_path, class: 'right btn-floating btn-large white-text' do
    i.ion-plus-round

.divider

.row
  -if @batch.invoices.empty?
     =link_to batch_process_path(@batch.id), class: 'btn col l3 offset-l4' do
       i.large-icon.ion-flash
       = " Processar Lote"
  -else
    table.table-striped
      thead
        tr
          th Código NF-e
          th Data
          th Horário
          th.center Visualizar

      tbody
        - @batch.invoices.each do |invoice|
          tr
            td = invoice.nfe_code
            td = invoice.created_at.strftime('%d/%m/%Y')
            td = invoice.created_at.strftime('%H:%M:%S')
            td.center
              = link_to batch do
                i.large-icon.ion-ios-eye

app/views/invoices/index.html.slim
h1 Invoice#index
p Find me in app/views/invoices/index.html.slim

app/views/invoices/show.html.slim
h1 Invoice#show
p Find me in app/views/invoices/show.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title Processador de NF-e
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    /! Nav Components
    = render 'layouts/con_theme/components/nav_bar'
    = render 'layouts/con_theme/components/nav_aside'

    section.content-wrap
      .card-panel
        =yield

app/views/layouts/con_theme/components/_circle_loader.html.slim
.circle_loader
  .preloader-wrapper.small.active
    .spinner-layer.spinner-blue
      .circle-clipper.left
        .circle
      .gap-patch
        .circle
      .circle-clipper.right
        .circle

    .spinner-layer.spinner-red
      .circle-clipper.left
        .circle
      .gap-patch
        .circle
      .circle-clipper.right
        .circle

    .spinner-layer.spinner-yellow
      .circle-clipper.left
        .circle
      .gap-patch
        .circle
      .circle-clipper.right
        .circle

    .spinner-layer.spinner-green
      .circle-clipper.left
        .circle
      .gap-patch
        .circle
      .circle-clipper.right
        .circle

app/views/layouts/con_theme/components/_error.html.slim
-# check if the errors exist to show it up
-if @error_obj
  -obj_name = @error_obj.class.name.downcase
  #error.alert
    -errors = @error_obj.errors.messages
    -errors.keys.each do |attr|
      -messages = errors[attr]
      p
        strong ="#{t("activerecord.attributes.#{obj_name}.#{attr}")}:"
      -messages = [messages] unless messages.is_a? Array
      ul
        -messages.each do |message|
          li =message.humanize

-# Reset the variables
-@error_obj=nil

app/views/layouts/con_theme/components/_nav_aside.html.slim
aside.yaybar.yay-shrink.yay-hide-to-small.yay-gestures.yay-light
  /! Brand & Close AsideMenu
  .top
    =render 'layouts/con_theme/structure/animated_exit'

  /! Menu Actions list
  .nano
    .nano-content
      ul.white
        /if @current_user.admin?
        /  @grouped_actions = admin_actions
        /else
        -@grouped_actions = aside_grouped_actions

        =render 'layouts/con_theme/components/nav_list'

app/views/layouts/con_theme/components/_nav_bar.html.slim
nav#application.navbar-top
  .nav-wrapper
    -@text_visual_identity = 'purple-text'
    /render 'layouts/partials/components/static/brand'
    =render 'layouts/con_theme/structure/profile'

app/views/layouts/con_theme/components/_nav_list.html.slim
-@grouped_actions = [@grouped_actions] unless @grouped_actions.is_a?Array
-@grouped_actions.each do |group|
  li.label =group[:label]
  -params[:action]=='index' ? action_controller = "#{params[:controller]}" : action_controller = "#{params[:controller]}.#{params[:action]}"
  -group[:actions].each do |action|
    li
      -action[:action_controller] == action_controller ? additional_class = 'active' : additional_class = nil
      a class="yay-sub-toggle waves-effect waves-amber #{additional_class}" href="#{action[:link]}"
        i class="#{action[:icon]}"
        -if action[:del]
          del=action[:name]
        -else
          =action[:name]

-# Reset partials variables
-@grouped_actions=nil

app/views/layouts/con_theme/components/_page_title.html.slim
.page-title
  .row
    .col.s12.m9.l10
      h1.purple-text =t "controllers.#{params[:controller]}"
      =render_breadcrumbs

      /! BreadCrumbs
        ul
          li
            a href="#"
              i class="fa fa-home" Home
              i class="fa fa-angle-right"
          li
            a href="dashboard.html" Dashboard

    /! Chat button
      .col.s12.m3.l2.right-align
        a.btn.grey.lighten-3.grey-text.z-depth-0.chat-toggle href="#!"
          i class="fa fa-comments"

app/views/layouts/con_theme/structure/_animated_exit.html.slim
a.yay-toggle href="#"
  .burg1
  .burg2
  .burg3

app/views/layouts/con_theme/structure/_profile.html.slim
/ul
/  li
/  li.user
/    /! User Profile link
/    a.dropdown-button href="#!" data-activates="user-dropdown"
/      /image_tag @current_user.picture, class: 'circle grey lighten-3'
/      /@current_user.name
/      i.mdi-navigation-expand-more.right
/
/    /! User Profile actions
/    ul#user-dropdown.dropdown-content
/      -profile_actions.each do |profile_action|
/        li
/          a.amber-text.text-darken-3 href="#{profile_action[:link]}"
/            i class="#{profile_action[:icon]}"
/            =profile_action[:name]
/      li.divider
/      li
/        a.amber-text.text-darken-3 href="#{destroy_user_session_path}"
/          i.fa.fa-sign-out
/          | Logout